package org.worldcubeassociation.tnoodle.server.webscrambles.pdf

import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfReader
import com.itextpdf.kernel.pdf.PdfWriter
import com.itextpdf.layout.Document
import com.itextpdf.layout.element.Paragraph
import com.itextpdf.layout.property.TextAlignment
import org.worldcubeassociation.tnoodle.server.webscrambles.pdf.util.FontUtil
import java.time.LocalDate
import kotlin.math.atan

class WatermarkPdfWrapper(
    val original: PdfContent,
    val creationTitle: String,
    val creationDate: LocalDate,
    val versionTag: String,
    val globalTitle: String?,
    val watermark: String? = null
) : BasePdfSheet() {
    override fun openDocument(writer: PdfWriter): PdfDocument {
        val reader = PdfReader(original.render().inputStream())

        return PdfDocument(reader, writer).apply {
            defaultPageSize = PAGE_SIZE
        }
    }

    override fun PdfDocument.writeContents() {
        val rawDoc = Document(this, PAGE_SIZE).apply {
            setMargins(0f, 75f, 0f, 75f) // FIXME correct order of args?
        }

        for (pageN in 1..numberOfPages) {
            val page = getPage(pageN)
            val rect = page.pageSizeWithRotation // FIXME there was an "art" param here before, useful?

            // Header
            val currentDate = creationDate.toString()
            rawDoc.showTextAligned(currentDate, rect.left, rect.top, TextAlignment.LEFT, 0f)

            val horizontalMiddle = (PAGE_SIZE.left + PAGE_SIZE.right) / 2
            rawDoc.showTextAligned(globalTitle, horizontalMiddle, PAGE_SIZE.top - 60, TextAlignment.CENTER, 0f)
            rawDoc.showTextAligned(creationTitle, horizontalMiddle, PAGE_SIZE.top - 45, TextAlignment.CENTER, 0f)

            if (numberOfPages > 1) {
                val pageNumFooter = "$pageN/$numberOfPages"

                rawDoc.showTextAligned(pageNumFooter, rect.right, rect.top, TextAlignment.RIGHT, 0f)
            }

            // Footer
            val generatedBy = "Generated by $versionTag"
            rawDoc.showTextAligned(generatedBy, horizontalMiddle, PAGE_SIZE.bottom + 40, TextAlignment.CENTER, 0f)

            // Staging watermark
            if (watermark != null) {
                val diagRotation = atan(PAGE_SIZE.height / PAGE_SIZE.width) //* (180f / PI)

                rawDoc.showTextAligned(Paragraph(watermark).setFont(FontUtil.NOTO_SANS_FONT).setFontSize(100f).setBold().setOpacity(0.2f).setRotationAngle(diagRotation),
                    horizontalMiddle, (PAGE_SIZE.top + PAGE_SIZE.bottom) / 2, TextAlignment.CENTER)
            }
        }
    }

    companion object {
        const val HEADER_AND_FOOTER_HEIGHT_RATIO = 12
    }
}
